# Generated by Django 4.2.1 on 2023-06-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_disppic_product_dispic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
